'use client';

import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Heart, Users, Briefcase, Sparkles, BookOpen, Brain } from 'lucide-react';

type QuestionCategory = 'family' | 'career' | 'love' | 'memories' | 'wisdom';

interface UserProfile {
  interests: string[];
  background: string;
  values: string[];
}

interface HeartfeltQuestionProps {
  userProfile: UserProfile;
  onComplete: (answer: string) => void;
  onSkip?: () => void;
}

interface GeneratedQuestion {
  category: QuestionCategory;
  question: string;
  context: string;
}

const CATEGORY_CONFIG: Record<QuestionCategory, { 
  label: string; 
  icon: React.ReactNode;
  colorClass: string;
  description: string;
}> = {
  family: {
    label: 'Family',
    icon: <Users size={18} />,
    colorClass: 'heartfelt-category-family',
    description: 'The bonds that shape who we are'
  },
  career: {
    label: 'Career',
    icon: <Briefcase size={18} />,
    colorClass: 'heartfelt-category-career',
    description: 'Your journey and achievements'
  },
  love: {
    label: 'Love',
    icon: <Heart size={18} />,
    colorClass: 'heartfelt-category-love',
    description: 'Relationships that matter most'
  },
  memories: {
    label: 'Memories',
    icon: <Sparkles size={18} />,
    colorClass: 'heartfelt-category-memories',
    description: 'Moments that defined you'
  },
  wisdom: {
    label: 'Wisdom',
    icon: <Brain size={18} />,
    colorClass: 'heartfelt-category-wisdom',
    description: 'Lessons learned along the way'
  }
};

// Sample questions by category (in production, these would be generated by AI)
const SAMPLE_QUESTIONS: Record<QuestionCategory, string[]> = {
  family: [
    "What's a tradition from your family that you hope will continue for generations?",
    "Who in your family has shaped who you are today, and what did they teach you?",
    "What's the most important lesson about love that you learned from your family?",
    "If you could preserve one family memory forever, which would it be and why?",
    "What do you want future generations of your family to know about where you came from?"
  ],
  career: [
    "What moment in your career made you feel most proud of who you've become?",
    "If you could share one piece of advice about work with your younger self, what would it be?",
    "What dream did you have for your career that actually came true?",
    "Who believed in you when you didn't believe in yourself, and how did that change everything?",
    "What would you want others to remember about your professional legacy?"
  ],
  love: [
    "How did you know when you found something real, and what did that feel like?",
    "What's the bravest thing you've ever done for love?",
    "If you could relive one perfect moment with someone you love, which would you choose?",
    "What has love taught you that nothing else could?",
    "How has your understanding of love evolved throughout your life?"
  ],
  memories: [
    "What memory instantly brings a smile to your face, no matter what?",
    "If you could bottle one moment from your life to experience again, which would it be?",
    "What seemingly small moment turned out to be incredibly significant?",
    "What's a memory that feels like it happened yesterday, even though years have passed?",
    "What experience changed the course of your life in ways you didn't expect?"
  ],
  wisdom: [
    "What's the hardest truth you've learned that you wish someone had told you sooner?",
    "If you could only pass down one lesson to the next generation, what would it be?",
    "What mistake taught you the most valuable lesson of your life?",
    "How has your definition of success changed over time?",
    "What do you know now about happiness that you didn't understand when you were younger?"
  ]
};

function generatePersonalizedQuestion(userProfile: UserProfile): GeneratedQuestion {
  // Select category based on user interests and background
  const categories: QuestionCategory[] = ['family', 'career', 'love', 'memories', 'wisdom'];
  
  // Simple matching logic - in production, use AI to generate truly personalized questions
  let selectedCategory: QuestionCategory = 'memories';
  
  const interests = userProfile.interests.map(i => i.toLowerCase());
  const background = userProfile.background.toLowerCase();
  
  if (interests.some(i => ['family', 'parent', 'child', 'mother', 'father', 'sister', 'brother'].includes(i)) || 
      background.includes('family')) {
    selectedCategory = 'family';
  } else if (interests.some(i => ['career', 'work', 'business', 'job', 'profession'].includes(i)) || 
             background.includes('work') || background.includes('career')) {
    selectedCategory = 'career';
  } else if (interests.some(i => ['love', 'relationship', 'partner', 'marriage', 'romance'].includes(i)) || 
             background.includes('love') || background.includes('married')) {
    selectedCategory = 'love';
  } else if (interests.some(i => ['wisdom', 'philosophy', 'teaching', 'mentor'].includes(i)) || 
             background.includes('teach') || background.includes('learn')) {
    selectedCategory = 'wisdom';
  }
  
  const questions = SAMPLE_QUESTIONS[selectedCategory];
  const randomQuestion = questions[Math.floor(Math.random() * questions.length)];
  
  return {
    category: selectedCategory,
    question: randomQuestion,
    context: `Based on your interest in ${userProfile.interests[0] || 'sharing your story'}`
  };
}

export function HeartfeltQuestion({ userProfile, onComplete, onSkip }: HeartfeltQuestionProps) {
  const [generatedQuestion, setGeneratedQuestion] = useState<GeneratedQuestion | null>(null);
  const [isGenerating, setIsGenerating] = useState(true);
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [answer, setAnswer] = useState('');
  const [showInput, setShowInput] = useState(false);

  // Generate personalized question on mount
  useEffect(() => {
    const timer = setTimeout(() => {
      const question = generatePersonalizedQuestion(userProfile);
      setGeneratedQuestion(question);
      setIsGenerating(false);
      
      // Start typewriter effect after a brief delay
      setTimeout(() => {
        setIsTyping(true);
      }, 500);
    }, 1500);

    return () => clearTimeout(timer);
  }, [userProfile]);

  // Typewriter effect for the question
  useEffect(() => {
    if (!isTyping || !generatedQuestion) return;

    const text = generatedQuestion.question;
    let index = 0;

    const typeInterval = setInterval(() => {
      if (index <= text.length) {
        setDisplayedText(text.slice(0, index));
        index++;
      } else {
        setIsTyping(false);
        // Show input field after question is fully typed
        setTimeout(() => {
          setShowInput(true);
        }, 400);
        clearInterval(typeInterval);
      }
    }, 35);

    return () => clearInterval(typeInterval);
  }, [isTyping, generatedQuestion]);

  const handleSubmit = useCallback(() => {
    if (answer.trim()) {
      onComplete(answer);
    }
  }, [answer, onComplete]);

  const config = generatedQuestion ? CATEGORY_CONFIG[generatedQuestion.category] : null;

  return (
    <div className="heartfelt-container max-w-2xl mx-auto">
      {/* Background decoration */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-[#406A56]/5 to-transparent rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-48 h-48 bg-gradient-to-tr from-[#D9C61A]/5 to-transparent rounded-full blur-3xl pointer-events-none" />

      {/* Content */}
      <div className="relative z-10">
        {/* Header */}
        <motion.div 
          className="text-center mb-8"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-[#406A56]/10 mb-4">
            <BookOpen size={28} className="text-[#406A56]" />
          </div>
          <h2 className="text-2xl font-semibold text-gray-800 mb-2">
            A Question Just for You
          </h2>
          <p className="text-gray-500 text-sm">
            Based on what you&apos;ve shared, we&apos;d love to hear more...
          </p>
        </motion.div>

        {/* Generating state */}
        <AnimatePresence mode="wait">
          {isGenerating ? (
            <motion.div
              key="generating"
              className="flex flex-col items-center justify-center py-12"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <motion.div
                className="w-12 h-12 border-3 border-[#406A56]/20 border-t-[#406A56] rounded-full"
                animate={{ rotate: 360 }}
                transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
              />
              <p className="mt-4 text-gray-500 font-handwritten text-lg">
                Crafting your question...
              </p>
            </motion.div>
          ) : generatedQuestion && config ? (
            <motion.div
              key="question"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              {/* Category Badge */}
              <motion.div 
                className="flex justify-center mb-6"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.2 }}
              >
                <span className={`heartfelt-category-badge ${config.colorClass}`}>
                  {config.icon}
                  {config.label}
                </span>
              </motion.div>

              {/* The Question with Typewriter Effect */}
              <div className="mb-8">
                <motion.h3 
                  className="heartfelt-question"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                >
                  {displayedText}
                  {isTyping && <span className="typewriter-cursor" />}
                </motion.h3>
              </div>

              {/* Answer Input */}
              <AnimatePresence>
                {showInput && (
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4 }}
                  >
                    <textarea
                      value={answer}
                      onChange={(e) => setAnswer(e.target.value)}
                      placeholder="Share your thoughts..."
                      className="w-full p-4 rounded-xl bg-white/80 border border-gray-200 
                                 text-gray-700 placeholder-gray-400 resize-none
                                 focus:outline-none focus:ring-2 focus:ring-[#406A56]/30 focus:border-[#406A56]/40
                                 transition-all"
                      rows={5}
                      autoFocus
                    />

                    {/* Actions */}
                    <div className="flex items-center justify-between mt-4">
                      {onSkip && (
                        <button
                          onClick={onSkip}
                          className="text-sm text-gray-400 hover:text-gray-600 transition-colors"
                        >
                          Skip for now
                        </button>
                      )}
                      
                      <button
                        onClick={handleSubmit}
                        disabled={!answer.trim()}
                        className="ml-auto flex items-center gap-2 px-6 py-2.5 
                                   bg-[#406A56] text-white rounded-xl font-medium
                                   hover:bg-[#355a48] disabled:opacity-50 disabled:cursor-not-allowed
                                   transition-all"
                      >
                        <Sparkles size={16} />
                        Share Your Story
                      </button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Category description */}
              {!showInput && (
                <motion.p 
                  className="text-center text-gray-400 text-sm mt-8"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.5 }}
                >
                  {config.description}
                </motion.p>
              )}
            </motion.div>
          ) : null}
        </AnimatePresence>
      </div>
    </div>
  );
}
